### ISSUE TITLE
Local search should accept and return a single `Individual`

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/python-gp#113]
I think from a user's perspective it makes more sense for all local search functions to accept and return a single individual. For example, the local search function updates parameters of the individual and finally returns it with updated parameters. All local search functions with otherwise need to implement the loop over the individuals, this would otherwise be hidden in the evolutionary algorithm.

Any strong opinion @mschmidt87? I'm assigning an early milestone since this changes the API for custom local searches.

**Comment by mschmidt87** [comment]
I agree, I've stumbled upon this myself.
